export const AUTH_LOGIN_USER = 'AUTH_LOGIN_USER';
export const AUTH_LOGOUT_USER = 'AUTH_LOGOUT_USER';
export const AUTH_LOGOUT_SUCCESSFUL = 'AUTH_LOGOUT_SUCCESSFUL';
export const AUTH_LOGIN_SUCCESSFUL = 'AUTH_LOGIN_SUCCESSFUL';
export const AUTH_LOAD_USER = 'AUTH_LOAD_USER';
export const AUTH_USER_LOADING = 'AUTH_USER_LOADING';
export const AUTH_USER_LOADED = 'AUTH_USER_LOADED';

export const BASE_SET_PROGRESS = 'BASE_SET_PROGRESS';
export const BASE_LOAD_KGS = 'BASE_LOAD_KGS';
export const BASE_SET_KGS = 'BASE_SET_KGS';
export const BASE_CHECK_KFS_ALIVE = 'BASE_CHECK_KFS_ALIVE';
export const BASE_SET_RES_TYPE = 'BASE_SET_RES_TYPE';
